name: Generate Release Notes

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:
    inputs:
      from_tag:
        description: 'Starting tag for range'
        required: false
        type: string
      to_tag:
        description: 'Ending tag'
        required: true
        type: string

jobs:
  generate-notes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Required to get all tags and history

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests atlassian-python-api PyGithub

      - name: Generate Release Notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CONFLUENCE_BASE_URL: ${{ vars.CONFLUENCE_BASE_URL || 'https://sinhaludyog.atlassian.net/wiki' }}
          CONFLUENCE_API_USER: ${{ vars.CONFLUENCE_API_USER || 's.kumar@kimbal.io' }}
          CONFLUENCE_API_TOKEN: ${{ secrets.CONFLUENCE_API_TOKEN }}
          SPACE_KEY: ${{ vars.SPACE_KEY || 'DAG' }}
          ANCESTOR_ID: ${{ vars.ANCESTOR_ID || '501776424' }}
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            python scripts/release_notes_generator.py --from-tag "${{ github.event.inputs.from_tag }}" --to-tag "${{ github.event.inputs.to_tag }}"
          else
            tag_name="${GITHUB_REF#refs/tags/}"
            python scripts/release_notes_generator.py --to-tag "$tag_name"
          fi
