name: Generate Release Notes and Publish to Confluence

# Trigger manually from Actions tab
on:
  workflow_dispatch:
    inputs:
      start_tag:
        description: 'Starting tag for release notes'
        required: true
        type: string
      end_tag:
        description: 'Ending tag for release notes'
        required: true
        type: string
      page_title:
        description: 'Confluence page title'
        required: true
        type: string
        default: 'Release Notes'
      exclude_authors:
        description: 'Comma-separated list of authors to exclude'
        required: false
        type: string
      jira_pattern:
        description: 'Filter commits by JIRA ticket pattern (default: all commits)'
        required: false
        type: string
        default: ''

jobs:
  generate-and-publish:
    runs-on: ubuntu-latest

    # Important: Before running this workflow, make sure to:
    # 1. Add CONFLUENCE_API_TOKEN as a repository secret
    # 2. Verify the CONFLUENCE_BASE_URL and CONFLUENCE_API_USER values
    # 3. Set the correct SPACE_KEY for your Confluence space

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for all tags and branches

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          pip install requests

      - name: Generate release notes and publish to Confluence
        env:
          CONFLUENCE_BASE_URL: "https://sinhaludyog.atlassian.net/wiki"
          CONFLUENCE_API_USER: "s.kumar@kimbal.io"
          CONFLUENCE_API_TOKEN: ${{ secrets.CONFLUENCE_API_TOKEN }}
          SPACE_KEY: "DAG"
          START_TAG: ${{ inputs.start_tag }}
          END_TAG: ${{ inputs.end_tag }}
          PAGE_TITLE: ${{ inputs.page_title }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          EXCLUDE_AUTHORS: ${{ inputs.exclude_authors }}
          JIRA_PATTERN: ${{ inputs.jira_pattern }}
        run: python scripts/generate_release_notes.py